title: CCG Lab Resources
description: A collection of lab resources for the Center for Comparative Genomics at the California Academy of Sciences
logo: /assets/CCG logo_color_horizontal.png
favicon_ico: /assets/CCG logo_blackonwhiteround.png
theme: just-the-docs

# External navigation links
nav_external_links:
  - title: Cal Academy Homepage
    url: https://www.calacademy.org/
    hide_icon: true # set to true to hide the external link icon - defaults to false
    opens_in_new_tab: false # set to true to open this link in a new tab - defaults to false
  - title: CCG Academy Website
    url: https://www.calacademy.org/scientists/ccg/ccg-lab-page
    hide_icon: true # set to true to hide the external link icon - defaults to false
    opens_in_new_tab: false # set to true to open this link in a new tab - defaults to false
  - title: CAS Intranet
    url: https://sites.google.com/calacademy.org/intranet/
    hide_icon: true 

# warnings, cautions, and notes settings
callouts_level: quiet # or loud
callouts:
  warning:
    title: WARNING!
    color: red
  caution:
    title: Caution!
    color: yellow
  note:
    title: Note
    color: blue
  greentip:
    title: Green Tip
    color: green


# Footer "Edit this page on GitHub" link text
back_to_top: true 
back_to_top_text: "Back to top"

gh_edit_link: true # show or hide edit this page link
gh_edit_link_text: "Edit this page on GitHub"
gh_edit_repository: "https://github.com/CCG-CAS/gh-pages" # the github URL for your repo
gh_edit_branch: "main" # the branch that your docs is served from
# gh_edit_source: docs # the source that your files originate from
gh_edit_view_mode: "tree" # "tree" or "edit" if you want the user to jump into the editor immediately

plugins:
  - jekyll-redirect-from
